language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: true

before_install:
  - python --version
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install build-essential
  - pip -V
  - pip install --upgrade pip
  - pip install setuptools
  - pip install coverage
  - pip install coveralls
  - pip install numpy
  - pip install pytest
  - pip install pytest-cov

install:
  - pip install -e .

script:
  - pytest --cov=./sfftk sfftk/unittests

after_success:
  - coveralls
