language: python

python:
  - "2.7"

sudo: true

before_install:
  - python --version
  - sudo apt-get update
  - sudo apt-get install build-essential
  - pip -V
  - pip install --upgrade pip
  - pip install setuptools
  - pip install coveralls

install:
  - python setup.py develop
  - sff --help

script:
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/sfftk/*" --omit="/home/travis/build/emdb-empiar/sfftk/sfftk/schema/v*.py","/home/travis/build/emdb-empiar/sfftk/sfftk/test_data","/home/travis/build/emdb-empiar/sfftk/sfftk/unittests" `which sff` tests all -v 3

after_success:
  - coveralls
